version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: chocoo_db
    environment:
      POSTGRES_USER: chocoo
      POSTGRES_PASSWORD: chocoo
      POSTGRES_DB: chocoo_skin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
